apiVersion: v1
appVersion: 6.4.3
name: grafana
version: v0.1.1

kubeVersion: ">=v1.15.0"
description: Helm Chart for grafana for the vulnerability-assessment-tool
keywords:
  - "SAP"
  - "vulnerability-assessment-tool"
  - "open-source"
  - "security-tools"
  - "java"
  - "python"
  - "maven"
  - "gradle"

home: https://sap.github.io/vulnerability-assessment-tool/
sources:
  - https://github.com/SAP/vulnerability-assessment-tool

maintainers:
  - name: "Quoc Trung HOANG"
    email: "quoc.trung.hoang@sap.com"
    url: ""

engine: gotpl
